# Generated by Django 3.2.8 on 2024-01-30 14:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, max_length=11)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 14, 40, 41, 556935))),
                ('updatedAt', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 14, 40, 41, 556961))),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.IntegerField()),
                ('t0', models.BigIntegerField(null=True)),
                ('t1', models.BigIntegerField(null=True)),
                ('t2', models.BigIntegerField(null=True)),
                ('t3', models.BigIntegerField(null=True)),
                ('t4', models.BigIntegerField(null=True)),
                ('t5', models.BigIntegerField(null=True)),
                ('t6', models.BigIntegerField(null=True)),
                ('t7', models.BigIntegerField(null=True)),
                ('t8', models.BigIntegerField(null=True)),
                ('t9', models.BigIntegerField(null=True)),
                ('t10', models.BigIntegerField(null=True)),
                ('t11', models.BigIntegerField(null=True)),
                ('t12', models.BigIntegerField(null=True)),
                ('t13', models.BigIntegerField(null=True)),
                ('t14', models.BigIntegerField(null=True)),
                ('t15', models.BigIntegerField(null=True)),
                ('t16', models.BigIntegerField(null=True)),
                ('t17', models.BigIntegerField(null=True)),
                ('t18', models.BigIntegerField(null=True)),
                ('t19', models.BigIntegerField(null=True)),
                ('t20', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='GroupBelong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=64, unique=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.group')),
            ],
            options={
                'db_table': 'GroupBelong',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member4', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member5', to='wxcloudrun.groupbelong'),
        ),
    ]
