# Generated by Django 3.2.8 on 2024-02-08 18:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Counters',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.IntegerField(null=True)),
                ('token_expire', models.DateTimeField(null=True)),
                ('credit', models.IntegerField(default=2100)),
                ('consumed', models.IntegerField(default=600)),
                ('exitable', models.BooleanField(default=True)),
                ('t0', models.BigIntegerField(null=True)),
                ('t1', models.BigIntegerField(null=True)),
                ('t2', models.BigIntegerField(null=True)),
                ('t3', models.BigIntegerField(null=True)),
                ('t4', models.BigIntegerField(null=True)),
                ('t5', models.BigIntegerField(null=True)),
                ('t6', models.BigIntegerField(null=True)),
                ('t7', models.BigIntegerField(null=True)),
                ('t8', models.BigIntegerField(null=True)),
                ('t9', models.BigIntegerField(null=True)),
                ('t10', models.BigIntegerField(null=True)),
                ('t11', models.BigIntegerField(null=True)),
                ('t12', models.BigIntegerField(null=True)),
                ('t13', models.BigIntegerField(null=True)),
                ('t14', models.BigIntegerField(null=True)),
                ('t15', models.BigIntegerField(null=True)),
                ('t16', models.BigIntegerField(null=True)),
                ('t17', models.BigIntegerField(null=True)),
                ('t18', models.BigIntegerField(null=True)),
                ('t19', models.BigIntegerField(null=True)),
                ('t20', models.BigIntegerField(null=True)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('price', models.IntegerField(default=0)),
                ('content', models.TextField(null=True)),
                ('question', models.TextField(null=True)),
            ],
            options={
                'db_table': 'hint',
            },
        ),
        migrations.CreateModel(
            name='Skip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('question_id', models.IntegerField(default=0)),
                ('cost', models.PositiveIntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.group')),
            ],
            options={
                'db_table': 'Skip',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('cost', models.PositiveIntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.group')),
                ('hint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.hint')),
            ],
            options={
                'db_table': 'Purchase',
            },
        ),
        migrations.CreateModel(
            name='GroupBelong',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=64, unique=True)),
                ('group_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.group')),
            ],
            options={
                'db_table': 'GroupBelong',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='member1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member3', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member4', to='wxcloudrun.groupbelong'),
        ),
        migrations.AddField(
            model_name='group',
            name='member5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member5', to='wxcloudrun.groupbelong'),
        ),
    ]
