# Generated by Django 3.2.8 on 2024-01-30 16:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='exitable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='group',
            name='token_expire',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 16, 53, 25, 855811)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 30, 16, 53, 25, 855839)),
        ),
        migrations.AlterField(
            model_name='group',
            name='token',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='groupbelong',
            name='group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.group'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2024, 1, 30, 16, 53, 25, 858056))),
                ('hint_id', models.IntegerField()),
                ('cost', models.PositiveIntegerField()),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.group')),
            ],
            options={
                'db_table': 'Purchase',
            },
        ),
    ]
