# Generated by Django 3.2.8 on 2024-02-03 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0002_auto_20240130_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'hint',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 6, 25, 42, 196340)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 6, 25, 42, 196350)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 6, 25, 42, 197211)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='hint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wxcloudrun.hint'),
        ),
    ]
