# Generated by Django 3.2.8 on 2024-02-03 08:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0003_auto_20240203_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='question',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 8, 52, 12, 68436)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 8, 52, 12, 68448)),
        ),
        migrations.AlterField(
            model_name='hint',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='hint',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='hint',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 8, 52, 12, 69643)),
        ),
    ]
