# Generated by Django 3.2.8 on 2024-02-03 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0004_auto_20240203_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 9, 0, 20, 530837)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 9, 0, 20, 530848)),
        ),
        migrations.AlterField(
            model_name='hint',
            name='question',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 3, 9, 0, 20, 531738)),
        ),
    ]
