# Generated by Django 3.2.8 on 2024-02-08 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0006_auto_20240208_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counters',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 21, 26, 140475)),
        ),
        migrations.AlterField(
            model_name='counters',
            name='updatedAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 21, 26, 140492)),
        ),
        migrations.AlterField(
            model_name='group',
            name='consumed',
            field=models.IntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='group',
            name='credit',
            field=models.IntegerField(default=2100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 21, 26, 141459)),
        ),
        migrations.AlterField(
            model_name='skip',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 8, 13, 21, 26, 141627)),
        ),
    ]
